apiVersion: v1
kind: Secret
metadata:
  name: mongodb
type: Opaque
data:
  MONGO_ROOT_USERNAME: YWRtaW4=
  MONGO_ROOT_PASSWORD: aW5pY2lhcjEyMzQ=
  MONGO_EM_USERNAME: ZW1vd25lcg==
  MONGO_EM_PASSWORD: cGFzc3dvcmQK
  MONGO_USERS_LIST: ZW1vd25lcjpkYkFkbWluLHJlYWRXcml0ZTppbmljaWFyMTIzNA==