#
#
# USE ONLY FOR DEV PURPOSE
#
#
apiVersion: v1
kind: Service
metadata:
  name: mongodb-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    component: mongodb
  